version: 1.0.{build}

branches:
  # whitelist 
  only:
    - master

test:
  assemblies:
    - src/UnitTesting/bin/$(configuration)/Dynamic.Decorator.UnitTesting.dll

before_build:
  - nuget restore src/Dynamic.Decorator.sln